In [1]:
import numpy as np
import pandas as pd
import json
import pickle

## Load Model

In [2]:
with open("KNN_model.pkl","rb") as f:
    model = pickle.load(f)

In [3]:
with open("Scaling.pkl","rb") as f:
    std = pickle.load(f)

## Test data

In [4]:
CRIM      =   0.05724
ZN         =  0.00000
INDUS      =  4.24000
CHAS       =  0.00000
NOX        =  0.46000
RM         =  6.33300
AGE       = 15.20000
DIS        =  7.21460
RAD        =  2.00000
TAX       = 450.00000
PTRATIO    = 17.90000
B          =370.21000
LSTAT      =  8.34000

In [9]:
# test_array = np.array([CRIM, ZN, INDUS, CHAS, NOX, RM, AGE, DIS, RAD, TAX,
#        PTRATIO, B, LSTAT],ndmin=2)

scaled_test_array = std.transform(test_array)
scaled_test_array

predicted_value = model.predict(scaled_test_array)[0]
predicted_value

C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


22.5625

In [15]:
test_array = np.array([CRIM, ZN, INDUS, CHAS, NOX, RM, AGE, DIS, RAD, TAX,
       PTRATIO, B, LSTAT])
test_array = np.array(test_array,ndmin=2)
test_array

array([[5.7240e-02, 0.0000e+00, 4.2400e+00, 0.0000e+00, 4.6000e-01,
        6.3330e+00, 1.5200e+01, 7.2146e+00, 2.0000e+00, 4.5000e+02,
        1.7900e+01, 3.7021e+02, 8.3400e+00]])

In [20]:
test_array[0] = CRIM
test_array[0][1] = ZN
test_array[0][2] = INDUS
test_array[0][3] = CHAS
test_array[0][4] = NOX
test_array[0][5] = RM
test_array[0][6] = AGE
test_array[0][7] = DIS
test_array[0][8] = RAD
test_array[0][9] = TAX
test_array[0][10] = PTRATIO
test_array[0][11] = B
test_array[0][12] = LSTAT


In [21]:
test_array

array([[5.7240e-02, 0.0000e+00, 4.2400e+00, 0.0000e+00, 4.6000e-01,
        6.3330e+00, 1.5200e+01, 7.2146e+00, 2.0000e+00, 4.5000e+02,
        1.7900e+01, 3.7021e+02, 8.3400e+00]])

In [22]:
scaled_test_array = std.transform(test_array)
scaled_test_array


C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.39082024, -0.46638308, -1.01884309, -0.28154625, -0.83142775,
         0.10661618, -1.93048266,  1.63784831, -0.86749   ,  0.2312442 ,
        -0.31127117,  0.15654678, -0.62637403]])

In [23]:

predicted_value = model.predict(scaled_test_array)[0]
predicted_value

C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


22.5625